title = "OS List"
baseURL = "https://example.com"
#theme = "researcher"

enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "Hyro"
  description = "Here you will find the OS with links."
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = "By Hyro, Contributors"
    url = "https://github.com/xHyroM/tools"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "Windows"
    url = "/other/windows"
    weight = 1
  [[menu.main]]
    name = "Linux"
    url = "/other/linux"
    weight = 2
  [[menu.main]]
    name = "Utilities"
    url = "/other/utilities"
    weight = 3

[markup.goldmark.renderer]
  unsafe = true

[[resources]]
  src = "**.md"